In [9]:
import numpy as np

In [10]:
data = np.array([[1, 2, 3, 4, 5, 6 ,7, 8, 9, 10],
                 [1, 2, 3, 4, 5, 6 ,7, 8, 9, 10]])

# the numpy arrays are fixed after initialization 
# the numpy array are homogeneous -> have same data type
# numpy arrays are stored in a sequence block of memory

print(data.shape)

(2, 10)


In [11]:
print(data.dtype)

int64


In [12]:
#create an array of ones np.ones((rows, coloumns))
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#create an array of zeros np.zeros((rows, coloumns))

zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#creating an identity matrix np.eye(number)

identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
# creating an array from a range np.arange(start, stop , step)

ranges = np.arange(1,10,2)
print(ranges)

[1 3 5 7 9]


In [16]:
#reading a file txt or csv

#file = np.loadtxt("file_name.csv",delimiter=',')

In [17]:
###indexing and slicing numpy array
#if it is a 1-d array we use slices like lists
#if the array is not one dimentional we use arr[row, col] to access the cell
#we can make subarrays from the original array without copying the whole dataframe 
# we just read from the same memory
#notice that any changes to the subarray will affect the original array

In [18]:
num_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print( f"the original array is {num_array}" )

the original array is [ 1  2  3  4  5  6  7  8  9 10]


In [19]:
#indexing the array

print(num_array[2:5])

[3 4 5]


In [20]:
#slicing the array

slice_array = num_array[2:5]

print(slice_array)

[3 4 5]


In [24]:
first = np.array([1, 2, 3])
sec = np.array([4, 5, 6])
third = np.array([7, 8, 9])

#addition
print(f"addition {first + sec + third}")

#subtraction
print(f"subtraction {third - first}")

#mulitplication
print(f"multplication {sec * first}")

#divistion
print(f"division {third / first}")


addition [12 15 18]
subtraction [6 6 6]
multplication [ 4 10 18]
division [7. 4. 3.]


In [25]:
#boolean indexing and masking

a = np.array([1, 2, 3, 4, 5])

mask = (a > 2) & (a < 5)

filtered_array = a[mask]

print(f"mask {mask}")

print(f"filtered array elements >2 and <5: {filtered_array}")


#modifying elements based on condition 
a[a > 3] = 10
print(f"modified array: {a}")

mask [False False  True  True False]
filtered array elements >2 and <5: [3 4]
modified array: [ 1  2  3 10 10]
