In [2]:
import numpy as np

In [ ]:
data = np.array([[1, 2, 3, 4, 5, 6 ,7, 8, 9, 10],
                 [1, 2, 3, 4, 5, 6 ,7, 8, 9, 10]])

# the numpy arrays are fixed after initialization 
# the numpy array are homogeneous -> have same data type
# numpy arrays are stored in a sequence block of memory

print(data.shape)

(2, 10)


In [5]:
print(data.dtype)

int64


In [9]:
#create an array of ones np.ones((rows, coloumns))
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
#create an array of zeros np.zeros((rows, coloumns))

zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#creating an identity matrix np.eye(number)

identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
# creating an array from a range np.arange(start, stop , step)

ranges = np.arange(1,10,2)
print(ranges)

[1 3 5 7 9]


In [14]:
#reading a file txt or csv

#file = np.loadtxt("file_name.csv",None ,",")